### PR TITLE
Implemented Code that gets maximum, minimum, and average cell temperatures

### PR DESCRIPTION
**Pull request by jatron**
Changed names of variables that end in cell_temp_C to end in cell_temp_dC
Implemented driver for FSAE's charge enable pin
Updated code that gets thermistor voltages to work with the new connector boards (the white ones)

The BMS compiles, has no warnings, and passes all tests.

### CODE REVIEW

**Comment by skoppula** [comment]
(1) You seem to have merge conflicts
(2) We'll need to properly implement separation of general purpose BMS code vs. FSAE specific code (either by compiler flags or keeping separate branches) before merging in. This is increasingly important if other teams (e.g. solar) and teams outside Edgerton use the BMS.

**Comment by jatron** [comment]
Thanks for the comments Skanda. I resolved the merge conflict and put all the FSAE specific code inside an FSAE_DRIVERS flag. 
The program compiles with no warnings and all tests pass with and without defining the FSAE_DRIVERS macro.

Let me know if there's anything else I should do before we merge the fsae branch into master.

**Comment by skoppula** [comment]
Haha, yes @jatron I noticed that nearly everything was wrapped in flags after posting the comment, why I deleted it, but you must've gotten the email notification...

Super big PR (700+ LoC!?). I'll need some time to review through it more closely. If possible, if you could do work on another sub-branch in the meantime, so that this PR doesn't get even bigger, would be helpful.

**Comment by jatron** [comment]
Sounds good. I'll start a new branch.

**Comment by skoppula** [comment]
Fix EEPROM pack_config order (and bump storage version up)

**Comment by skoppula** [comment]
Put https://github.com/MITEVT/ltc-battery-management-system/blob/0da15fd9a6178d35c2d04c5d9d622b22df3da356/src/board.c#L65 into the FSAE preprocessor flags on line 52

[FIXED]

**Comment by skoppula** [comment]
https://github.com/MITEVT/ltc-battery-management-system/pull/17/files#diff-3407be8d0b1d6afd21d723114647ef6eR27

Is it possible to put the guards around the function definition too?

**Comment by skoppula** [comment]
Nitpicky, remove space: https://github.com/MITEVT/ltc-battery-management-system/pull/17/files#diff-deb5b65288cbe791420badb651257b71R225

**Pull request merged**
